/**
 * Canonical Job Card System (CJCS) Types — v2.0
 *
 * Mirrors lib-conxian-core::cjcs canonical types (src/cjcs.rs). These TypeScript
 * types are the platform-side representation of Conxian's Job Card Schema.
 *
 * ## Core Type Alignment
 * - `JobCard` ↔ `lib_conxian_core::cjcs::JobCard { context, r#type, work_intent }`
 * - `WorkIntent` ↔ `lib_conxian_core::cjcs::WorkIntent { sender_address, receiver_address, task_id, amount_sbtc }`
 * - `TrustTier` ↔ `lib_conxian_core::control_model::TrustTier { Strict, Managed, Expedient, ObserverOnly }`
 *
 * ## Clarity Contract Integration
 * - `sla-enforcer.clar`: monitors JobCards against Stacks block deadlines
 * - `referral-aggregator.clar`: Sovereign Swarm 95/5 referral yield splits
 *
 * ## Enterprise Mappings
 * - SAP BAPI: material_number, plant_code, purchasing_group
 * - Oracle REST: oracleRestEndpoint for gap job card posting
 *
 * Wire path: conxius-platform → cjcs.ts → lib-conxian-core::cjcs
 *            → sla-enforcer.clar → referral-aggregator.clar
 */

/** Trust tier per CON-791. Mirrors lib-conxian-core::control_model::TrustTier. */
export type TrustTier = 'Strict' | 'Managed' | 'Expedient' | 'ObserverOnly';

/** Job Card lifecycle states per v2.0 spec. */
export type JobCardState =
  | 'Draft'
  | 'Published'
  | 'Assigned'
  | 'InProgress'
  | 'Completed'
  | 'Verified'
  | 'Disputed'
  | 'Cancelled';

/** SLA breach severity levels. */
export type SlaSeverity = 'Warning' | 'Breach' | 'Critical';

/**
 * Canonical Work Intent — mirrors lib-conxian-core::cjcs::WorkIntent.
 *
 * ```rust
 * pub struct WorkIntent {
 *     pub sender_address: String,
 *     pub receiver_address: String,
 *     pub task_id: String,
 *     pub amount_sbtc: u64,
 * }
 * ```
 */
export interface WorkIntent {
  /** Stacks principal address of the job creator. */
  senderAddress: string;
  /** Stacks principal address of the worker/assignee. */
  receiverAddress: string;
  /** Unique task identifier (UUID). */
  taskId: string;
  /** Reward in sats (sBTC). Mirrors `amount_sbtc: u64`. */
  amountSbtc: number;
}

/**
 * Canonical Job Card — mirrors lib-conxian-core::cjcs::JobCard.
 *
 * ```rust
 * pub struct JobCard {
 *     pub context: String,
 *     pub r#type: String,
 *     pub work_intent: WorkIntent,
 * }
 * ```
 */
export interface JobCard {
  /** Human-readable job context/description. */
  context: string;
  /** Job type classification. */
  type: string;
  /** Work intent: sender, receiver, task, reward. */
  workIntent: WorkIntent;
  /** Unique job card identifier (UUID, platform-assigned). */
  id: string;
  /** Current lifecycle state (platform-assigned, not in core struct). */
  state: JobCardState;
  /** Trust tier (platform-assigned, from control_model::TrustTier). */
  trustTier: TrustTier;
  /** Stacks block height when the job was created. */
  createdAtBlock: number;
  /** Stacks block height deadline for completion. */
  deadlineBlock: number;
  /** Stacks block height when completed (if done). */
  completedAtBlock?: number;
}

/** SLA enforcement record — generated by sla-enforcer.clar. */
export interface SlaRecord {
  jobCardId: string;
  checkBlock: number;
  blocksRemaining: number;
  severity: SlaSeverity;
  slashPercent: number;
  triggerGapJobCard: boolean;
}

/** Sovereign Swarm referral record — generated by referral-aggregator.clar. */
export interface ReferralRecord {
  jobCardId: string;
  referrer: string;
  worker: string;
  totalYieldUstx: number;
  referrerShareUstx: number;
  workerShareUstx: number;
}

/** SAP BAPI-compatible enterprise job card extension. */
export interface EnterpriseJobCard extends JobCard {
  materialNumber?: string;
  plantCode?: string;
  purchasingGroup?: string;
  oracleRestEndpoint?: string;
}
