/**
 * Canonical Job Card System (CJCS) Types — v2.0
 *
 * Mirrors lib-conxian-core::cjcs canonical types. These TypeScript types are
 * the platform-side representation of Conxian's Job Card Schema, used for:
 * - SLA enforcement (sla-enforcer.clar)
 * - Autonomous gap job card generation (Satori <70% bottleneck)
 * - Sovereign Swarm referral-aggregator yield splits
 * - SAP BAPI / Oracle REST field mapping for enterprise integration
 *
 * Wire path: conxius-platform → CJCS TypeScript types → lib-conxian-core::cjcs
 *            → sla-enforcer.clar → referral-aggregator.clar
 *
 * @see docs/CJCS_v2.0_SPEC.md
 * @see lib-conxian-core/src/cjcs.rs
 */

/** Trust tier classification per CON-791. */
export type TrustTier = 'Strict' | 'Managed' | 'Expedient';

/** Job Card lifecycle states. */
export type JobCardState =
  | 'Draft'
  | 'Published'
  | 'Assigned'
  | 'InProgress'
  | 'Completed'
  | 'Verified'
  | 'Disputed'
  | 'Cancelled';

/** SLA breach severity levels. */
export type SlaSeverity = 'Warning' | 'Breach' | 'Critical';

/** Canonical Job Card — mirrors lib-conxian-core::cjcs::JobCard. */
export interface JobCard {
  /** Unique job card identifier (UUID). */
  id: string;

  /** Human-readable title. */
  title: string;

  /** Full job description / specification. */
  description: string;

  /** Stacks principal address of the job creator. */
  creator: string;

  /** Stacks principal address of the assigned worker (if assigned). */
  assignee?: string;

  /** Current lifecycle state. */
  state: JobCardState;

  /** Trust tier for this job (determines verification requirements). */
  trustTier: TrustTier;

  /** Reward in micro-STX. */
  rewardUstx: number;

  /** Stacks block height when the job was created. */
  createdAtBlock: number;

  /** Stacks block height deadline for completion. */
  deadlineBlock: number;

  /** Stacks block height when the job was completed (if completed). */
  completedAtBlock?: number;

  /** Arbitrary metadata for SAP/Oracle field mappings. */
  metadata: Record<string, string>;
}

/** SLA enforcement record — generated by sla-enforcer.clar. */
export interface SlaRecord {
  /** The job card this SLA record monitors. */
  jobCardId: string;

  /** Current block height at time of check. */
  checkBlock: number;

  /** Blocks remaining until deadline. Negative = overdue. */
  blocksRemaining: number;

  /** Current SLA status. */
  severity: SlaSeverity;

  /** Yield slashing percentage if breached. */
  slashPercent: number;

  /** Whether this breach triggers autonomous gap job card generation. */
  triggerGapJobCard: boolean;
}

/** Sovereign Swarm referral record — generated by referral-aggregator.clar. */
export interface ReferralRecord {
  /** Referred job card ID. */
  jobCardId: string;

  /** Referrer principal (95% of yield). */
  referrer: string;

  /** Worker principal (5% of yield). */
  worker: string;

  /** Total yield from this job in micro-STX. */
  totalYieldUstx: number;

  /** Referrer's share in micro-STX. */
  referrerShareUstx: number;

  /** Worker's share in micro-STX. */
  workerShareUstx: number;
}

/**
 * SAP BAPI-compatible enterprise job card mapping.
 * Ensures CJCS fields map 1:1 with SAP Business API and Oracle REST fields.
 */
export interface EnterpriseJobCard extends JobCard {
  /** SAP material number or Oracle inventory item ID. */
  materialNumber?: string;

  /** SAP plant code or Oracle organization ID. */
  plantCode?: string;

  /** SAP purchasing group or Oracle buying group. */
  purchasingGroup?: string;

  /** Oracle-specific REST endpoint for gap job card posting. */
  oracleRestEndpoint?: string;
}
