name: Secret Scan

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'CODEOWNERS'
      - 'LICENSE'
    branches: [ main, staged, dev ]
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'CODEOWNERS'
      - 'LICENSE'
    branches: [ main, staged, dev ]

permissions:
  contents: read

jobs:
  gitleaks:
    uses: ./.github/workflows/reusable-secret-scan.yml
    permissions:
      contents: read
